spring:
  application:
    name: leco-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8080
dubbo:
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: user-provider